### ISSUE TITLE
Multi-line comment bug in VS 2017

### ISSUE THREAD

**Issue by fahadabdulaziz** [jgyo/remarker#2]
Hi, 

Really useful extension. Thank you very much for it.
Sadly I have an issue with multi-line comments :
![screenshot_2](https://user-images.githubusercontent.com/5483584/27587793-6bc13312-5b4e-11e7-93a3-06246795b781.png)

Thanks

**Comment by jgyo** [comment]
Thank you for your comment. Unfortunately, this is the way multiline comments work. The modifiers to produce line sizes and color changes just come at the beginning of the comment. To change each line, you need to use single line comments.
